<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://aaaws.mycompany.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="ServerImplService" targetNamespace="http://aaaws.mycompany.com/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://aaaws.mycompany.com/" elementFormDefault="unqualified" targetNamespace="http://aaaws.mycompany.com/" version="1.0">

  <xs:element name="getBankClients" type="tns:getBankClients"/>

  <xs:element name="getBankClientsResponse" type="tns:getBankClientsResponse"/>

  <xs:complexType name="getBankClients">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="getBankClientsResponse">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="getBankClientsResponse">
    <wsdl:part element="tns:getBankClientsResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getBankClients">
    <wsdl:part element="tns:getBankClients" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ServerInterface">
    <wsdl:operation name="getBankClients">
      <wsdl:input message="tns:getBankClients" name="getBankClients">
    </wsdl:input>
      <wsdl:output message="tns:getBankClientsResponse" name="getBankClientsResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ServerImplServiceSoapBinding" type="tns:ServerInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getBankClients">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getBankClients">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getBankClientsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ServerImplService">
    <wsdl:port binding="tns:ServerImplServiceSoapBinding" name="ServerImplPort">
      <soap:address location="http://localhost:8080/BankServer"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>